SELECT IDCLIENTE, MES, ANIO, COUNT(*) AS COMPRAS
FROM( SELECT NUMERO, IDCLIENTE, EXTRACT(DAY FROM FECHA) AS DIA, EXTRACT(MONTH FROM FECHA) AS MES, EXTRACT(YEAR FROM FECHA) AS ANIO  
      FROM A_FACTURA
      WHERE SUCURSAL = 1)
      GROUP BY IDCLIENTE, MES, ANIO
      HAVING COUNT(*) >= 2
      ORDER BY MES ASC, ANIO ASC
      
      
COMMIT;